language: node_js
sudo: true
dist: trusty
node_js:
- '6.11'
- '7.10'
- '10'
- node
install:
- yarn
script: npm run test
notifications:
  email:
    on_failure: change
  slack:
    rooms:
      secure: WRQ7937b1e3IE6XelR5Uxmca9oV4EjIdR24ZtJW037SCnyIUP7LtX15dYZwuvOxoT0AsIpRDhA1GiMIXOvlIdwTnfqb2DQM1zf9qEAgA3z8TXXk58iArLfryUCGe+SX25ybkr6NaLOYvJLNr0KaiCG4Sc7BGSfRPoDM8zP1HyUpC/BCL9aNXumGwptXZKDak4u4AnoOGlf7T6v2k5uZLh5cJhtpsL4FAYJrWapzJGHOmfxqz88BhIIVbEhkkVZn983jBM8feBsHrrBo7z8kHl72De2/G8eL0DkSvr2hTGNMNfIIHsncbF0YbKbXkUgezCPoTVnYUgqFly4k8TOKl5PbVRSdxM+RJ8/yTY18IZMycncxlLjmgCtW904YpwJiQzZwQ73G/L2sHaM3kxyoj2axa51XnX5UsKyXtY6jF7Tw/X8/D1UCuVmcNKF+92fCbJjA7bNheHPptHiiW2nOREeZh9pKS2i6PxupZ4LyDJXSaGDMKBChBbOUk8XDsVKZXsoO65Y9tiTh3hrcrH2qW4aM1arhPaX/dSgSpCuZAinNsbpYCLGLqonxpuDwtnmhNUbVNiQe01vxCo2sOzVOyq5dBLpReTi4WORZXprOeDZyoGZ3avEfVoDA51hHw0melUE3RXc3B7h6VK8P4yAb8Tm7U4p996RLBSk3ueyDFHKo=
after_success:
- "./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls"
